version: '3'
services:
  mysql-container:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: demo_api_root_Mechoigame-12
      MYSQL_DATABASE: demo_api
      MYSQL_USER: root
      MYSQL_PASSWORD: Mechoigame-12
    ports:
      - "3306:3306"

  spring-boot-app:
    build: .
    depends_on:
      - mysql-container
    ports:
      - "8080:8080"
